# ARRAYS

In [1]:
import array as arr

In [3]:
a=arr.array('i',[2,3,5]) #creating an array a

In [4]:
a

array('i', [2, 3, 5])

In [5]:
b=arr.array('i',[3,6,9])

In [6]:
b

array('i', [3, 6, 9])

# SLICING

In [7]:
a[2:] #slicing

array('i', [5])

In [8]:
a[::-1]  #reverse

array('i', [5, 3, 2])

In [15]:
b.append(12)

In [16]:
b

array('i', [3, 6, 9, 12])

In [18]:
b.pop()

12

In [19]:
b.pop(0)
b

array('i', [6, 9])

In [20]:
b.remove(6)
b


array('i', [9])

In [25]:
for i in b:
    print( i,end="")

9

In [26]:
a+b #concatenation

array('i', [2, 3, 5, 6, 6, 9])

# NUMPY
*pip install numpy

In [27]:
import numpy as np

In [28]:
k=np.array([(1,2,3),(2,4,6)])
m=np.array([(3,6,9),(4,8,12)])
k

array([[1, 2, 3],
       [2, 4, 6]])

In [29]:
m

array([[ 3,  6,  9],
       [ 4,  8, 12]])

In [30]:
m.ndim     #to check the dimensions

2

In [31]:
m.itemsize    #to know the size of each element

4

In [32]:
k.dtype

dtype('int32')

In [33]:
m.shape

(2, 3)

In [34]:
k.reshape(3,2)

array([[1, 2],
       [3, 2],
       [4, 6]])

In [35]:
m.size

6

In [36]:
m.min

<function ndarray.min>

In [37]:
m.min(1)

array([3, 4])

In [38]:
m.min()

3

In [39]:
m.max()

12

In [40]:
m.sum()

42

In [41]:
g=np.linspace(1,8,15)
g

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. ])

In [42]:
m.sum(axis=0)

array([ 7, 14, 21])

In [43]:
m.sum(axis=1)

array([18, 24])

In [44]:
np.sqrt(m)

array([[1.73205081, 2.44948974, 3.        ],
       [2.        , 2.82842712, 3.46410162]])

In [45]:
np.std(m)

3.0550504633038935

In [46]:
np.mean(k)

3.0

In [47]:
k

array([[1, 2, 3],
       [2, 4, 6]])

In [48]:
k[0,2]

3

In [49]:
k[0:2,1]  #zeroth row first row

array([2, 4])

In [50]:
k[1,2]

6

In [51]:
k[k>2]

array([3, 4, 6])

In [53]:
m[m<=6]

array([3, 6, 4])

In [54]:
k.sort()
k

array([[1, 2, 3],
       [2, 4, 6]])

In [55]:
k+m

array([[ 4,  8, 12],
       [ 6, 12, 18]])

In [56]:
k%m

array([[1, 2, 3],
       [2, 4, 6]], dtype=int32)